# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('RAM', models.CharField(max_length=30)),
                ('Core', models.IntegerField()),
                ('Storage', models.CharField(max_length=30)),
            ],
        ),
    ]
