# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=120, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
