# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20161003_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MacNum', models.CharField(max_length=30)),
                ('ServerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Server')),
            ],
        ),
    ]
