# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_mac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='id',
        ),
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='Un Known', max_length=30, primary_key=True, serialize=False),
        ),
    ]
