# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20161004_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='ServerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macs', to='blogs.Server'),
        ),
    ]
