# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20161019_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='RacNum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
