# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_server_racnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='Core',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='server',
            name='RacNum',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=1),
        ),
    ]
