# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20161024_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('RacNum', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
