# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20161024_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='RacNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rac', to='blogs.Rac'),
        ),
    ]
