# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20161024_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='RacNum',
        ),
        migrations.AddField(
            model_name='server',
            name='Rac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='racs', to='blogs.Rac'),
            preserve_default=False,
        ),
    ]
