# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-24 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20161024_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='Rac',
            new_name='RacNum',
        ),
    ]
