# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20161106_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rac',
            old_name='RacNum',
            new_name='RackNum',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='RacNum',
            new_name='RackNum',
        ),
    ]
